# https://taskfile.dev

version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - npm i

  default:
    deps: [install]
    aliases: [s, start]
    cmds:
      - npm run dev

  build:
    deps: [install]
    cmds:
      - npm run build

  build:giscus-theme:
    deps: [install]
    aliases: [bgt]
    cmds:
      - npm run build:giscus-theme

  preview:
    deps: [build]
    cmds:
      - npm run preview

  lint:fix:
    deps: [install]
    cmds:
      - npm run lint:fix
