name: Build and Deploy | 构建并部署

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy | 构建并部署
    runs-on: ubuntu-latest
    if: github.repository == 'misitebao/static-theme-misipage'

    steps:
      - name: Checkout | 切换到部署分支
        uses: actions/checkout@v2
        with:
          ref: 'main'
          submodules: true

      - name: Setup Node | 设置 Node 环境
        uses: actions/setup-node@v3
        with:
          hugo-version: '16'

      - name: Build Site| 构建网站
        run: |
          npm install
          npm run build

      - name: Deploy to Server | 部署到服务器
        uses: hengkx/ssh-deploy@v1.0.1
        with:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_HOST_USER }}
          PASSWORD: ${{ secrets.DEPLOY_HOST_PASSWORD }}
          SOURCE: 'dist'
          TARGET: ${{ secrets.DEPLOY_TARGET }}
